/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/furniture/platform_bed/platform_bed.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/platform_bed.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.076, 0.056, 0.055]} scale={0.013}>
        <mesh geometry={nodes.Material2.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Material2001.geometry} material={materials.material_18} />
        <mesh geometry={nodes.Material2002.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Material2003.geometry} material={materials.wooden_floor} />
      </group>
      <group position={[-0.076, 0.056, 0.055]} scale={0.013}>
        <mesh geometry={nodes['big-pillow'].geometry} material={materials.material_39} />
        <mesh geometry={nodes.Material3078.geometry} material={materials.material_40} />
        <mesh geometry={nodes.pillow.geometry} material={materials.material_39} />
      </group>
      <group position={[-0.076, 0.056, 0.055]} scale={0.013}>
        <mesh geometry={nodes.Material2102.geometry} material={materials.material_39} />
        <mesh geometry={nodes.Material3079.geometry} material={materials.material_40} />
        <mesh geometry={nodes.Material2104.geometry} material={materials.material_37} />
      </group>
      <group position={[-0.076, 0.056, 0.055]} scale={0.013}>
        <mesh geometry={nodes.Material2105.geometry} material={materials.wooden_floor} />
        <mesh geometry={nodes.Material2106.geometry} material={materials.Aluminum} />
        <mesh geometry={nodes.Material3081.geometry} material={materials.material} />
      </group>
      <group position={[-0.076, 0.056, 0.055]} scale={0.013}>
        <mesh geometry={nodes.Material2160.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2161.geometry} material={materials.material} />
        <mesh geometry={nodes.Material3129.geometry} material={materials.white_mosaic} />
        <mesh geometry={nodes.Material3130.geometry} material={materials.white_mosaic} />
      </group>
      <group position={[-0.076, 0.056, 0.055]} scale={0.013}>
        <mesh geometry={nodes.Material2168.geometry} material={materials.material_39} />
        <mesh geometry={nodes.Material3137.geometry} material={materials.material_40} />
        <mesh geometry={nodes.Material2170.geometry} material={materials.material_37} />
        <mesh geometry={nodes.Material2171.geometry} material={materials.material_35} />
      </group>
      <mesh geometry={nodes.pillow001.geometry} material={materials['material_39.001']} position={[-0.076, 0.056, 0.055]} scale={0.013} />
      <mesh geometry={nodes.pillow002.geometry} material={materials['material_39.002']} position={[-0.076, 0.056, 0.055]} scale={0.013} />
      <mesh geometry={nodes.pillow003.geometry} material={materials['material_39.003']} position={[-0.076, 0.056, 0.055]} scale={0.013} />
      <mesh geometry={nodes['removable-pillow'].geometry} material={materials['material_39.004']} position={[-0.076, 0.056, 0.055]} scale={0.013} />
    </group>
  )
}

useGLTF.preload('/platform_bed.gltf')
